### ISSUE TITLE
Update to serverless v4 and serverless-compose?

### ISSUE THREAD

**Issue by DasBen** [zirkelc/serverless-output-plugin#2]
```
npm error While resolving: example@0.0.0
npm error Found: serverless@4.4.12
npm error node_modules/serverless
npm error   dev serverless@"4.4.12" from the root project
npm error
npm error Could not resolve dependency:
npm error peer serverless@"^3.0.0" from serverless-exports-plugin@1.2.0
npm error node_modules/serverless-exports-plugin
npm error   dev serverless-exports-plugin@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

Is there any chance this plugin gets updated to serverless v4?

**Comment by DasBen** [comment]
Ok that was way easier to fix than i thought.

All that is needed for sls v4 support is one line:

```
  "peerDependencies": {
    "serverless": "^3.0.0"
  }
```

  to
  
```
  "peerDependencies": {
    "serverless": "^3.0.0 || ^4.0.0"
  }
```

But sadly the plugin is not working with serverless-compose. Any fix for that?

**Comment by zirkelc** [comment]
Hey @DasBen I just published a new npm version 1.3.0 with Serverlesss v4 as peer deps.

Regarding serverless-compose: I'm still using Serverless v3 and have no experience with serverless-compose. Please feel free to create a PR to support it.

**Comment by DasBen** [comment]
You are a monster :D that was way to fast to fix this. Big thanks! serverless-compose works but only if you have the export within the service serverless config. Now i have 3 .env and stack outputs :D but at least it works.

I'll close this one.

**Comment by zirkelc** [comment]
Glad it works for you! 👍
